name: signin_options
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase Core (Required for any Firebase service)
  firebase_core: ^3.5.0
  cloud_functions: ^5.6.2

  # Firebase Authentication
  firebase_auth: ^5.6.0
  
  # Firebase Realtime Database
  firebase_database: ^11.0.1

  # Firestore
  cloud_firestore: ^5.5.0

  # Firebase Storage
  firebase_storage: ^12.1.4

  # Firebase Messaging
  firebase_messaging: ^15.1.0

  # Google Sign-In
  google_sign_in: ^6.2.2

  # Local Notifications
  flutter_local_notifications: ^17.2.2

  # Facebook Sign-In
  flutter_facebook_auth: ^7.1.2

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  googleapis_auth: ^1.6.0
  uuid: ^4.4.0

  # Image Picker
  image_picker: ^1.1.2
  flutter_dotenv: ^5.1.0
  device_info_plus: ^10.1.1

  # Cached Image Loading
  cached_network_image: ^3.3.1
  http: ^1.2.2

  # Date/Time Formatting
  intl: ^0.20.0
  permission_handler: ^11.3.1

  # Shared Preferences
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/service-account.json
